# Generated by Django 6.0.6 on 2026-07-06 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["created_at"], "verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество просмотров",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.CheckConstraint(
                condition=models.Q(("views__gte", 0)),
                name="views_must_be_positive",
                violation_error_message="Views must be positive value",
            ),
        ),
    ]
