# Generated by Django 6.0.6 on 2026-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_alter_blogpost_views_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blogpost",
            name="views_must_be_positive",
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.CheckConstraint(
                condition=models.Q(("views__gte", 0)),
                name="views_must_be_positive",
                violation_error_message="Views must be positive value",
            ),
        ),
    ]
