# Generated by Django 6.0.6 on 2026-06-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category_name",
                    models.CharField(
                        help_text="Введите наименование категории продуктов",
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование категории",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        help_text="Введите описание категории продуктов", verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_name",
                    models.CharField(
                        help_text="Введите наименование продукта", max_length=250, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_description",
                    models.TextField(help_text="Введите описание продукта", verbose_name="Описание продукта"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изобрадение продукта",
                        null=True,
                        upload_to="products/",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите цену продукта",
                        max_digits=10,
                        verbose_name="Цена за покупку",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите катагорию продуктов",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["product_name"],
            },
        ),
    ]
