# Generated by Django 6.0.6 on 2026-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contact_country",
                    models.CharField(help_text="Введите название страны", max_length=50, verbose_name="Страна"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Введите наименование контакта", max_length=150, verbose_name="Наименование"
                    ),
                ),
                ("contact_address", models.CharField(help_text="Введите адрес", max_length=250, verbose_name="Адрес")),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(help_text="Введите номер телефона", max_length=15, verbose_name="Телефон"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["contact_country"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="products/",
                verbose_name="Изображение продукта",
            ),
        ),
    ]
