# Generated by Django 6.0.6 on 2026-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback_username", models.CharField(max_length=150, verbose_name="Имя")),
                ("feedback_phone", models.CharField(max_length=15, verbose_name="Телефон")),
                ("feedback_message", models.TextField(verbose_name="Сообщение")),
                ("processed", models.BooleanField(default=False, verbose_name="Обработан")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывыы",
                "ordering": ["created_at"],
            },
        ),
    ]
