# Generated by Django 6.0.6 on 2026-06-30 07:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["created_at"], "verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Введите цену продукта",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01000000000000000020816681711721685132943093776702880859375")
                    )
                ],
                verbose_name="Цена за покупку",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(condition=models.Q(("price__gt", 0)), name="price_must_be_positive"),
        ),
    ]
