# Generated by Django 6.0.6 on 2026-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_feedback_options_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="product",
            name="price_must_be_positive",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)),
                name="price_must_be_positive",
                violation_error_message="Product price must be positive",
            ),
        ),
    ]
