# Generated by Django 6.0.6 on 2026-07-06 06:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_price_must_be_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={"min_value": "Product price must be positive"},
                help_text="Введите цену продукта",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01000000000000000020816681711721685132943093776702880859375")
                    )
                ],
                verbose_name="Цена за покупку",
            ),
        ),
    ]
